# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "ce98790a-829d-4a31-bd56-c3c496c6bb0f"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "tripinsightsvaultteam2"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: sqlpass
          objectAlias: SQL_PASSWORD
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: sqlserver
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
    tenantId: "94a74401-f0cc-436d-a9b7-e5ca7a338d08"          # The tenant ID of the key vault