apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
status:
  loadBalancer: {}