apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: userapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userapi
status:
  loadBalancer: {}